
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/danial/OS/Prog/clion/CLion-2023.3.3/clion-2023.3.3/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.5.0-35-generic - x86_64
...
